import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Rordle",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className + " flex flex-col items-center "}>
				<img
					className="fixed top-0 left-0 w-full h-full object-cover bg-center z-[-1] blur-sm scale-110"
					src="/rorBG.jpg"
				/>
				<div className="bg"></div>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
